### ISSUE TITLE
Student in administrator module

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#108]
Be sure before start that this resource has been finished in previous releases.
Implement ACL for resources in administrator module. If you start assign the issue to yourself and comment here 'started'.
Add role and user on controller level.
PHPUnit rests for restrictions and access if any are shown in [https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md](https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md)
Tests in Student and Administrator should remain working.
When all is done please comment here 'done'.

**Comment by juhankoks** [comment]
Started

**Comment by juhankoks** [comment]
Should be done
