### ISSUE TITLE
ContactLesson in Core\Entity create unittest

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#126]
Examples Core\Entity\Absence and CoreTest\Entity\AbsenceTest.
Cover all properties and methods.
Use typehinting, (LisUser $createdBy), and type casting, $this->trashed = (int) $trashed, where possible and needed
Comment all properties and methods.

**Comment by Ellucy** [comment]
Finished

**Comment by reposandermets** [comment]
Not finished. removeSubjectRound and addSubjectRound not tested also missing typehint. same goes for addAbsence($absence) and removeAbsence($absence)

**Comment by Ellucy** [comment]
Typehint is not missing
