### ISSUE TITLE
Rooms in Core\Entity create unittest

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#133]
Examples Core\Entity\Absence and CoreTest\Entity\AbsenceTest.
Cover all properties and methods.
Use typehinting, (LisUser $createdBy), and type casting, $this->trashed = (int) $trashed, where possible and needed.
Comment all properties and methods.

**Comment by alaraasa** [comment]
started

**Comment by alaraasa** [comment]
finished
