### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by alaraasa** [parnustk/lisbackend#211]
Choosing language between ET and EN

**Comment by reposandermets** [comment]
Please remove flags - they are not needed. There will be 2 places in views for language switcher - in login form and in menu, both are in the scope of loginController. If current language is  Estonian then Switcher should display English. When English is clicked window.LisGlobals.L will have value 'en' and page will be reloaded. And vice versa. It would be nice if  preferred lang would be saved inside cookie. Start in FE administrator app.

**Comment by reposandermets** [comment]
good job.
