### ISSUE TITLE
BackupDB Front End login

### ISSUE THREAD

**Issue by MartenKahr** [parnustk/lisbackend#216]
Start with login logic.

**Comment by reposandermets** [comment]
Relevant files for viws are module/BackupDB/view/layout/layout.phtml as container. Action based(testAction) view can be found in module/BackupDB/view/backup-db. We can't use .htaccess cause we have single start direcory. Probably simple form and static login could be used.
Relevant documentation(db thing is not needed, only using form, and getting data from POST request)
[http://framework.zend.com/manual/current/en/user-guide/forms-and-actions.html](http://framework.zend.com/manual/current/en/user-guide/forms-and-actions.html)

**Comment by reposandermets** [comment]
Do not use cookie, use session instead. see LisAuth [https://github.com/parnustk/lisbackend/blob/master/module/LisAuth/src/LisAuth/Service/LisAuthService.php](https://github.com/parnustk/lisbackend/blob/master/module/LisAuth/src/LisAuth/Service/LisAuthService.php) about using Zend Session.

**Comment by reposandermets** [comment]
Closing thi issue. if any bugs new issue should be created.
