### ISSUE TITLE
LisUser managment for super administrator

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#225]
Create view with all LisUsers. Administrator can change password and email for user. Administrator can assoiciate LisUser to teacher/administrator/student - better to delete and create user. no need to update.

**Comment by reposandermets** [comment]
Admin should be able to update LisUser email and password.

**Comment by KristenEST** [comment]
getList update delete lisUserController in administrator BE

**Comment by KristenEST** [comment]
Still ToDo change grid password field to asterisk only and not hash.

**Comment by KristenEST** [comment]
ToDo if not superadmin redirect with an error

**Comment by reposandermets** [comment]
password hash should not be shown

**Comment by reposandermets** [comment]
password not shown.
