### ISSUE TITLE
Move DB credential to zend2 global config file

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#226]
Move DB credential to zend2 global config file, DB access passwords should be not in repository. Also line. 
Docs can be found [http://framework.zend.com/manual/current/en/modules/zend.config.reader.html](http://framework.zend.com/manual/current/en/modules/zend.config.reader.html)

Also approach define("_PATH_", "/home/marten/LIS_workspace/lisbackend/data/BackupDB_Dumps/"); should be relative path not static, therefore  /home/marten/LIS_workspace/lisbackend/ is not countable as final solution.

**Comment by MartenKahr** [comment]
Complete
