### ISSUE TITLE
set up Jenkins to lis.ee

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#229]
Consult with Sander before starting. 

There are already places for new lis copies. find directories for test, demo, alpha etc all lis clones should have separate databases.

**Comment by reposandermets** [comment]
1. test.lis.ee - all by Jenkins, running phpunit tests. Base language ET
2. alpha.lis.ee  - Jenkins only updates from repository. Base language ET
3. beta.lis.ee  - showing for client, manual update. Base language ET
4. demo.lis.ee - manual update. Base language EN
All clones should have separate database and virtualhosts. Finally current lisbackend will be removed and replaced by empty .html file..

**Comment by reposandermets** [comment]
let lisbackend remain for 2 weeks.

**Comment by juhankoks** [comment]
Sadly we can not use Jenkinks on our current webhosting due on low memory.
