### ISSUE TITLE
Administrator view lessons given by teacher. lesson report.

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#237]
Specially requested view by Ele. Work through http://ui-grid.info/docs/#/tutorial/105_footer.  Prototype can be found [https://raw.githubusercontent.com/parnustk/lisbackend/master/data/lessonview/PrintScreen.jpg](https://raw.githubusercontent.com/parnustk/lisbackend/master/data/lessonview/PrintScreen.jpg). Start with planning the extra DQL method. See student grades view in student app, FE and BE for reference. DQL should start from SubjectRound or ContactLesson repository.  Count operation can be done in front end or in dql - take time to analyse and discuss with Sander if needed.  Also which filters will be needed - techer filter defenetly, but what else?

**Comment by alaraasa** [comment]
Front-end showing table and most data. Back-end started DQL. Translations.
https://github.com/parnustk/lisbackend/commit/1e3086e88c9845129dc73354db19df5f76b9250d

**Comment by reposandermets** [comment]
does not count correctly AK. Maybe should ask from subjectround instead of contactlesson. SQL needs degugging.

**Comment by reposandermets** [comment]
BE is ready review here line 96 [https://github.com/parnustk/lisbackend/blob/master/module/Core/src/Core/Entity/Repository/ContactLessonRepository.php](https://github.com/parnustk/lisbackend/blob/master/module/Core/src/Core/Entity/Repository/ContactLessonRepository.php)  
FE TODO required filter is teacherId, optional filters are startDate and endDate - three fields into filterForm.
don't loadData() if teacher is not selected.

**Comment by reposandermets** [comment]
start and enddate example is here [https://github.com/parnustk/lisbackend/blob/master/public/app/student/lis/dist/templates/absence.html](https://github.com/parnustk/lisbackend/blob/master/public/app/student/lis/dist/templates/absence.html) and here [https://github.com/parnustk/lisbackend/blob/master/public/app/student/lis/src/app/controller/absenceController.js](https://github.com/parnustk/lisbackend/blob/master/public/app/student/lis/src/app/controller/absenceController.js)
