### ISSUE TITLE
Internship report final version

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#242]
Create Word document in onedrive. Share it with all team members. My [live.com](live.com) user is sandermets@live.com . You can find content from [https://github.com/parnustk/lisbackend/blob/master/data/ET_PRAKTIKA_RAPORT.md](https://github.com/parnustk/lisbackend/blob/master/data/ET_PRAKTIKA_RAPORT.md) . Create correct title page.

**Comment by alaraasa** [comment]
https://onedrive.live.com/redir?resid=46E948128D848229!114&authkey=!AGIk8dbAzU8tmvM&ithint=file%2cdocx
