### ISSUE TITLE
BackupdDb delete dumpfiles older than a week

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#275]
Please remove dumpfiles what are more than week old - both generated and uploaded dumps.

code hint:
$date     = new DateTime($filedateString);
$interval = new DateInterval('P1W');

if(! (new DateTime() < $date->add($interval))){//new DateTime is TODAY
    //delete the file
}

[http://stackoverflow.com/questions/17068380/php-get-date-a-week-ago](http://stackoverflow.com/questions/17068380/php-get-date-a-week-ago)

**Comment by MartenKahr** [comment]
Closed
