### ISSUE TITLE
BackupDB empty upload returns success and printscrees

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#276]
reproduce: dont select any filest and press upload
you get something like 
/Users/mobiledev/Documents/lweb/module/BackupDB/src/BackupDB/Controller/DumpController.php:127:
array (size=5)
  'name' => string '' (length=0)
  'type' => string '' (length=0)
  'tmp_name' => string '' (length=0)
  'error' => int 4
  'size' => int 0
UPLOAD SUCCESS
Return to Panel

**Comment by MartenKahr** [comment]
Closed
