### ISSUE TITLE
Internship report

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#61]
https://github.com/parnustk/lisbackend/blob/master/data/ET_PRAKTIKA_RAPORT.md Write under headers with your name.

**Comment by reposandermets** [comment]
goes to Juhan

**Comment by juhankoks** [comment]
goes to Marten

**Comment by MartenKahr** [comment]
goes to Sander

**Comment by reposandermets** [comment]
goes to Eleri

**Comment by Ellucy** [comment]
Done a lot, goes to Sander

**Comment by reposandermets** [comment]
Kristen takes meanwhile.

**Comment by KristenEST** [comment]
Goes to Alar

**Comment by alaraasa** [comment]
Goes to Sander.
