### ISSUE TITLE
Student in student module

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#73]
Implement role and user based approach  -setup createdBy and updatedBy. See Absence as an example. Main work is in repository and Controllertest class.
Test restricions if any are shown in [https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md](https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md). Tests in Administrator class shoud remain working.

**Comment by MartenKahr** [comment]
Started

**Comment by reposandermets** [comment]
finished
