### ISSUE TITLE
Teacher in teacher module

### ISSUE THREAD

**Issue by reposandermets** [parnustk/lisbackend#88]
Implement ACL for resources in teacher module. If you start assign the issue to yourself and comment here 'started'.
Be sure before start that this resource has been finished in student module
Test restrictions if any are shown in [https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md](https://github.com/parnustk/lisbackend/blob/master/BEFRACL.md)
Tests in Student module should remain working.
Tests in Administrator module should remain working.
When all is done please comment here 'done'

**Comment by juhankoks** [comment]
Started

**Comment by juhankoks** [comment]
Should be ready.
